services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: dev
      MARIADB_DATABASE: cloud

    volumes:
      - mariadbdata:/var/lib/mysql
volumes:
  mariadbdata:
